### PR TITLE
Adding hubot-trello

### PR DESCRIPTION
**Pull request by joemcl**
See https://github.com/hubot-scripts/hubot-trello

### CODE REVIEW

**Comment by joemcl** [comment]
I also added these to the config/env variables - 
HUBOT_TRELLO_KEY    - Trello application key
HUBOT_TRELLO_TOKEN  - Trello API token
HUBOT_TRELLO_BOARD  - The ID of the Trello board you will be working with

**Comment by joemcl** [comment]
Also final instruction at https://github.com/hubot-scripts/hubot-trello  is 'Run npm install' - assume I can just run that from the console window again? I tried 'npm install --save hubot-trello' at first but that failed

**Comment by xurizaemon** [comment]
Hey @joemcl, on a bus at mo.

I suggest:

- clone the repo locally from heroku
- `npm i hubot-trello`
- `heroku config:set <whatever>`
- git commit & push to heroku > restarts bolts

This will mean we install a specific version of the Trello plugin (see versions of other items in package.json).

Also need to add the plugin to external-scripts.json so Hubot loads it.

You should be good to push to the repo on heroku and I'll set you up to push here - but it's fine to open a pull request if you want review!

You can also `heroku local` if you want to test locally, pause on heroku to do this or there will be two bolts!

**Comment by xurizaemon** [comment]
Huh ok I see your comments now

Will try myself :)

**Pull request merged**
